### ISSUE TITLE
Warning message on start up

### ISSUE THREAD

**Issue by tuxmaster5000** [reconquest/atlassian-external-hooks#113]
Every time the server starts, the following warning is logged:

> WARN  [Caesium-1-2]  c.n.stash.externalhooks.HooksFactory created 0 hook scripts on scope repository=XXX/XXX

For every repo in very project one of it is logged, when the project or the repo has not enabled the hook.

**Comment by kovetskiy** [comment]
@tuxmaster5000 Hi, yes, we've made intentionally. Does it cause any problems on your side?

Back in the day, there was no such entity as HookScript in Bitbucket, but nowadays we can't execute hooks inside git repositories as we used to do, but now we have this completely separated system of "hook scripts" which is not controlled in any way in the user interface (hooks, on the other hand, can be disabled), so we decided to log all actions related to this hook scripts system with warning severity because in case of any troubles you can always collect these logs.

**Comment by tuxmaster5000** [comment]
Yes, our monitoring system will send alert messages, because the WARNING tag.
When it only tagged as INFO then all will be fine.

**Comment by kovetskiy** [comment]
Hi, we've just released the new version that fixes the issue, please check version 10.2.1.

You can also find it here: https://marketplace.atlassian.com/apps/1211631/external-hooks-by-reconquest/version-history#
