### ISSUE TITLE
License renewal & trial

### ISSUE THREAD

**Issue by cshaw100** [reconquest/atlassian-external-hooks#129]
Hello, we have a 1000 user server license of External Hooks which expires May 23rd 2022. We purchased this through Atlassian. We would to extend this until April 1st 2023, which is when we plan to move to the Atlassian Cloud, at which point we will buy the cloud version of External Hooks. Can you please sell us the license for that period of time? Atlassian said they would not give us a license for less than a year. 
Also would it be possible to get a trial license of the cloud version, and if so how long could we have it for, obviously the longer the better for us.
Thanks and regards, Chris Sha

**Comment by kovetskiy** [comment]
Hello, could you try to delete the existing trial license from the existing add-on configuration in the Bitbucket admin panel, save the configuration, then try to request the trial again?

> Can you please sell us the license for that period of time? Atlassian said they would not give us a license for less than a year.
Unfortunately, there is no way to do so on our end because of the fact that Atlassian actually takes care of all the purchases and controls the marketplace, we don't have much of flexibility when it comes to such requests. 

> Also would it be possible to get a trial license of the cloud version, and if so how long could we have it for, obviously the longer the better for us.
The add-on doesn't work for cloud version of Bitbucket due to the fact that there is no technical possibility to intercept git objects the same way we do in Server/Data_Center versions.

**Comment by kovetskiy** [comment]
Feel free to re-open the issue if you still have any questions.
