### ISSUE TITLE
External Async Post Receive Hook run synchronouslly

### ISSUE THREAD

**Issue by estebangit** [reconquest/atlassian-external-hooks#97]
Bitbucket server V6.4.0
External Hooks V6.6.0-1

Since we upgraded from the free version (3.4-1) of the plugin to the payed one, our _External Async Post receive hooks_ are executed in a synchronous mode. This causes huge delays for all the _git push_.

**Comment by seletskiy** [comment]
@estebangit: Hi, thanks for the report. Post-receive hook is now running in sync mode due internal changes made by Atlassian in BB Server hook scripts architecture.

We're looking into workaround for this problem right now, will reach you ASAP.

**Comment by kovetskiy** [comment]
@estebangit we've just released the fix for your issue. You can download it from official marketplace https://marketplace.atlassian.com/apps/1211631/external-hooks/version-history#b6312 or upgrade it through "Manage Apps" page in your Bitbucket installation.

You just need to click **Asynchronous** in Post Receive Hook settings tab that you can find on the screenshot.

![2019-09-09-14T12T29](https://user-images.githubusercontent.com/8445924/64526732-c1713180-d30c-11e9-9347-1589684dc2b4.png)

Let us know if you have any questions.

**Comment by estebangit** [comment]
@kovetski Thanks to release quickly a fix. 
The fix restore the asynchronous behaviour, but for some repositories, it calls the script correctly, but the while loop exit immediately. In synchronous mode it works as expected.

(
while read from_ref to_ref ref_name; do
   ...
done
) >>/log/my-script.log

**Comment by kovetskiy** [comment]
@estebangit I'm closing this one since you've created #98 which describes your issue.
